on:
  release:
    types: [released]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create generic version tag based on release tag
        run: |
          echo "tag_name=$(echo ${{ github.ref_name }} | sed -E 's/^(v[0-9]+)\.[0-9]+\.[0-9]+$/\1/')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Create generic tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ env.tag_name }}
